const fs = require("node:fs");
"use strict";
const assert = require("node:assert/strict");
const page = fs.readFileSync("src/static/dashboard/control-tower.html", "utf8");
const api = fs.readFileSync("src/api.py", "utf8");
assert.deepEqual([...new Set([...page.matchAll(/data-choice="([^"]+)"/g)].map((match) => match[1]))], ["manufacturing", "stock"]);
assert.doesNotMatch(page, /data-state=/);
assert.doesNotMatch(page, /[\u00c2\u00c3]/);
assert.doesNotMatch(page, /const entry|salesOrder\.cx.*stockSteps/);
for (const label of ["Estimasi / RKB Kasar", "Quotation", "Sales Order", "Fulfilment", "Delivery", "Invoice", "Payment", "Manufacturing Order", "From Stock / Internal Order", "RKB Pekerjaan", "Cek Stock", "ROP", "Purchase Order", "Receipt &amp; QC", "Internal Order", "Stock Material", "Manufacture", "Finished Goods", "Kembali ke gambaran besar", "opsional sebelum SO", "bukan syarat From Stock"]) assert.ok(page.includes(label), label);
assert.doesNotMatch(page, /owner visual review|Review flow|1\. Overview|2\. Fulfilment expanded|3\. MO journey|4\. Stock \/ IO journey/);
assert.match(page, /route reference/);
assert.match(page, /id="salesOrderFindingBadge"/);
assert.match(page, /loadSalesOrderFindingBadge/);
assert.match(page, /findingFilters/);
assert.match(page, /salesOrderNode/);
assert.match(page, /stockChoice\.cx.*elbowY.*internalOrder\.cx.*internalOrder\.top/s);
assert.match(page, /stockChoice/);
assert.match(page, /data-key="fulfilment".*?addEventListener/s);
assert.match(page, /prefers-reduced-motion/);
assert.match(page, /overflow-x: auto/);
assert.match(page, /Geser untuk melihat alur/);
assert.match(page, /<button class="node fulfilment"[^>]*type="button"[^>]*aria-expanded="false"[^>]*aria-controls="fulfilment-choices"[^>]*aria-label="Tampilkan pilihan Fulfilment"/);
assert.match(page, /<div class="choices" id="fulfilment-choices">/);
assert.match(page, /fulfilmentControl\.setAttribute\('aria-expanded', String\(state !== 'overview'\)\)/);
assert.match(page, /fulfilmentControl\.addEventListener\('click', \(\) => apply\(currentState === 'overview' \? 'expanded' : 'overview'\)\)/);
assert.doesNotMatch(page, /fulfilmentControl\.addEventListener\('(keydown|keyup)'/);
assert.match(page, /<div class="map-viewport">\s*<div class="map-scroll"[\s\S]*?<\/div>\s*<div class="scroll-cue"[^>]*>Geser untuk melihat alur/);
assert.match(page, /mapViewport\.classList\.toggle\('has-overflow', mapScroll\.scrollWidth > mapScroll\.clientWidth \+ 1\)/);
assert.match(page, /mapScroll\.addEventListener\('scroll', \(\) => mapViewport\.classList\.toggle\('has-scrolled', mapScroll\.scrollLeft > 4\)\)/);
assert.match(api, /@app\.get\("\/dashboard\/control-tower"/);
console.log("Integrated Process Map correction checks passed");
