const assert = require('node:assert/strict');
const fs = require('node:fs');

const page = fs.readFileSync('src/static/dashboard/control-tower.html', 'utf8');
const shell = fs.readFileSync('src/static/dashboard/control-tower-shell.js', 'utf8');
const salesOrders = fs.readFileSync('src/static/dashboard/sales-orders.js', 'utf8').replaceAll(String.fromCharCode(13), '');
const salesOrdersHtml = fs.readFileSync('src/static/dashboard/sales-orders.html', 'utf8');
assert.match(page, /class="ct-immersive-page"/);
assert.match(page, /data-ct-temuan/);
assert.match(page, /data-ct-inspector/);
assert.match(page, /data-ct-open-documents/);
assert.match(page, /data-process-key="sales-order"/);
assert.match(page, /data-process-key="manufacturing-order"/);
assert.match(page, /data-process-key="material-purchase-order"/);
assert.match(shell, /function evidenceStateForNode/);
assert.match(shell, /function coverageMessageForNode/);
assert.match(shell, /function categoryDestination/);
assert.match(shell, /presentation_category/);
assert.match(shell, /return_to/);
assert.ok(salesOrders.includes('returnToControlTower'));
assert.ok(salesOrdersHtml.includes('id="returnToControlTower"'));
assert.ok(salesOrders.includes('function safeReturnPath'));
assert.ok(salesOrders.includes('raw.startsWith("//")'));
assert.ok(salesOrders.includes('parsed.origin !== window.location.origin'));
assert.ok(salesOrders.includes('decodeURIComponent'));
const helperMatch = salesOrders.match(/(function safeReturnPath\(raw\) \{[\s\S]*?\n\})\n\nfunction configureReturnAction/);
assert.ok(helperMatch);
const safeReturnPath = new Function('window', `${helperMatch[1]}; return safeReturnPath;`)({ location: { origin: 'https://dashboard.test' } });
assert.equal(safeReturnPath('/dashboard/control-tower?selected_process=sales-order'), '/dashboard/control-tower?selected_process=sales-order');
assert.equal(safeReturnPath('https://evil.example/dashboard/control-tower'), '');
assert.equal(safeReturnPath('//evil.example/dashboard/control-tower'), '');
assert.equal(safeReturnPath('/dashboard/control-tower?bad=%E0%A4%A'), '');
console.log('Immersive Control Tower static contracts passed');
