const assert = require('node:assert/strict');
const fs = require('node:fs');

const page = fs.readFileSync('src/static/dashboard/control-tower.html', 'utf8');
const salesOrders = fs.readFileSync('src/static/dashboard/sales-orders.js', 'utf8').replaceAll(String.fromCharCode(13), '');
const salesOrdersHtml = fs.readFileSync('src/static/dashboard/sales-orders.html', 'utf8');
assert.match(page, /class="temuan-panel"/);
assert.match(page, /id="integratedFindingList"/);
assert.match(page, /id="salesOrderFindingBadge"/);
assert.match(page, /class="inspector-panel"/);
assert.match(page, /affected_model: 'sale\.order'/);
assert.match(page, /category: 'DATA_BELUM_LENGKAP'/);
assert.match(page, /rule_code: 'DH2-SALES-001'/);
assert.match(page, /current_status/);
assert.match(page, /actualEvidence/);
assert.match(page, /selected_finding/);
assert.match(page, /return_to/);
assert.match(page, /integratedFindingRetry/);
assert.match(page, /Temuan yang dipilih tidak ditemukan/);
assert.ok(page.includes('/api/control-tower/evidence'));
assert.match(page, /MASALAH_AKTIF/);
assert.match(page, /PERLU_DITINJAU/);
assert.match(page, /DATA_BELUM_LENGKAP/);
assert.match(page, /inspectorClassification/);
assert.match(page, /inspectorRawEvidence/);
assert.match(page, /process-evidence-badge/);
assert.match(page, /Destination belum tersedia/);
assert.ok(page.includes('category_counts'));
assert.ok(page.includes('presentation_category'));
assert.ok(page.includes('data-process-key="material-purchase-order"'));
assert.match(page, /stockChoice\.cx.*elbowY.*internalOrder\.cx.*internalOrder\.top/s);
assert.ok(page.includes('payload.total'));
assert.ok(page.includes('findingQuery(currentFindings.length)'));
assert.ok(page.includes('integratedFindingLoadMore'));
assert.ok(page.includes('selectedProcessKey'));
assert.ok(page.includes('restoreSelectedProcess'));
assert.ok(page.includes('exactFindingDestination(finding)'));
assert.ok(salesOrders.includes('returnToControlTower'));
assert.ok(salesOrdersHtml.includes('id="returnToControlTower"'));
assert.ok(salesOrders.includes('function safeReturnPath'));
assert.ok(salesOrders.includes('raw.startsWith("//")'));
assert.ok(salesOrders.includes('parsed.origin !== window.location.origin'));
assert.ok(salesOrders.includes('decodeURIComponent'));
const helperMatch = salesOrders.match(/(function safeReturnPath\(raw\) \{[\s\S]*?\n\})\n\nfunction configureReturnAction/);
assert.ok(helperMatch);
const safeReturnPath = new Function('window', `${helperMatch[1]}; return safeReturnPath;`)({ location: { origin: 'https://dashboard.test' } });
assert.equal(safeReturnPath('/dashboard/control-tower?selected_process=sales-order'), '/dashboard/control-tower?selected_process=sales-order');
assert.equal(safeReturnPath('https://evil.example/dashboard/control-tower'), '');
assert.equal(safeReturnPath('//evil.example/dashboard/control-tower'), '');
assert.equal(safeReturnPath('/dashboard/control-tower?bad=%E0%A4%A'), '');
console.log('Integrated three-panel static contracts passed');
