const fs = require("node:fs");
"use strict";
const assert = require("node:assert/strict");
const page = fs.readFileSync("src/static/dashboard/control-tower.html", "utf8");
const api = fs.readFileSync("src/api.py", "utf8");
assert.deepEqual([...new Set([...page.matchAll(/data-choice="([^"]+)"/g)].map((match) => match[1]))], ["manufacturing", "stock"]);
assert.doesNotMatch(page, /data-state=/);
assert.doesNotMatch(page, /[\u00c2\u00c3]/);
assert.doesNotMatch(page, /const entry|salesOrder\.cx.*stockSteps/);
for (const label of ["Estimasi / RKB Kasar", "Quotation", "Sales Order", "Fulfilment", "Delivery", "Invoice", "Payment", "Manufacturing Order", "From Stock / Internal Order", "RKB Pekerjaan", "Cek Stock", "ROP", "Purchase Order", "Receipt &amp; QC", "Internal Order", "Stock Material", "Manufacture", "Finished Goods", "Kembali ke gambaran besar", "opsional sebelum SO", "bukan syarat From Stock"]) assert.ok(page.includes(label), label);
assert.doesNotMatch(page, /owner visual review|Review flow|1\. Overview|2\. Fulfilment expanded|3\. MO journey|4\. Stock \/ IO journey/);
assert.match(page, /route reference/);
assert.match(page, /stockChoice/);
assert.match(page, /data-key="fulfilment".*?addEventListener/s);
assert.match(page, /prefers-reduced-motion/);
assert.match(page, /overflow-x: auto/);
assert.match(page, /Geser untuk melihat alur/);
assert.match(api, /@app\.get\("\/dashboard\/control-tower"/);
console.log("Integrated Process Map correction checks passed");
